#!/bin/python
import sys
""" The dictionary of folders and their path shown initially """
folders = {
        "Home":"/home/farzeen",
        "Gallery":"/mnt/gallery",
        "Data":"/mnt/data"
        }

DMENU = "dmenu"
DMENU_OPTS = ['-i']
DMENU_OPTS.extend(sys.argv[1:])

FIND = "find"

def dmenu(prompt=None, extra_opts=None, input=None):
    cmd = [DMENU]
    if prompt is not None: cmd.extend(['-p',prompt])
    if DMENU_OPTS is not None: cmd.extend(DMENU_OPTS)
    if extra_opts is not None: cmd.extend(extra_opts)

    process = subprocess.Popen(cmd,
            stdout=subprocess.PIPE,
            stdin=subprocess.PIPE,universal_newlines=True)

    (stdout,stderr) = process.communicate(input=input)
    return process.returncode,stdout,stderr


def find(path,iname=None):
    cmd=[FIND]
    cmd.extend(path)
    if iname is not None: cmd.extend(["-iname",iname])

    process = subprocess.Popen(cmd,stdout=subprocess.PIPE,universal_newlines=True)

    (stdout,stderr) = process.communicate()
    return process.returncode,stdout,stderr

print ("TODO!")
