#!/bin/bash

result="RETRY"

dmenu_bin="dmenu"
dmenu_opts="-fn \"Droid Sans Mono-8\""

until [ "$result" != "RETRY" ]; do

  dmenu_complete="$dmenu_bin $dmenu_opts -i -p 'List of available networks' -l 5"
  connection=$(nmcli -t --field NAME con| eval $dmenu_complete)
  if [ $? -ne 0 ]; then exit 0; fi

  message=$(nmcli --ask con up id "$connection" 2>&1)
  if [ $? -ne 0 ]; then
    dmenu_complete="$dmenu_bin $dmenu_opts -i -p \"$message\""
    result=$(printf "OK\nRETRY" | eval $dmenu_complete)
  else
    result="OK"
  fi

done
