#!/bin/python
import subprocess
import i3ipc
import re

stdout, stderr = subprocess.Popen(
    ['dmenu', '-i', '-fn', "Droid Sans Mono-8", '-p', "Rename workspace to:"],
    stdout=subprocess.PIPE,
    stdin=subprocess.PIPE,
    universal_newlines=True).communicate(
        input="Web-Dev Web Dev Zeal Android VBox Files Music Video Term Sys".
        replace(' ', '\n'))

stdout = stdout.strip()

i3 = i3ipc.Connection()
w = i3.get_tree().find_focused().workspace()
name = str(w.name)
index = int(re.findall('[0-9]+', name)[0])
if len(stdout)>0:
    payload='rename workspace "%s" to "%d: %s"' % (name, index, stdout)
else:
    payload='rename workspace "%s" to "%d"' % (name,index)

i3.message(message_type=i3ipc.MessageType.COMMAND,
           payload=payload)
