#!/bin/bash

wifi_hw_stat=`nmcli -t --fields WIFI-HW r`

cpu_max=`cat /sys/devices/system/cpu/intel_pstate/max_perf_pct`
cpu_min=`cat /sys/devices/system/cpu/intel_pstate/min_perf_pct`

echo \
"WiFi Hardware: $wifi_hw_stat
 CPU Min: $cpu_min %
 CPU Max: $cpu_max %\
" | dmenu -l 5 -p "System Status"

