#!/bin/python
import urllib.parse
import sys
import os

if len(sys.argv)<2:
    print("Removes google url from the given url and print it.")
    binary = sys.argv[0]
    binary = binary[binary.rfind(os.sep)+1:]
    print("Usage: {0} <url-with-google-redir>".format(binary))
    exit(0)
u=sys.argv[1]
print(urllib.parse.unquote(u[u.find('url=')+4:u.find('&',u.find('url='))]))
