#!/bin/bash

BLUEZCARD=`pactl list cards short | egrep -o "bluez_card.[A-Z0-9_]+"`
pactl set-card-profile $BLUEZCARD a2dp_sink
pactl set-card-profile $BLUEZCARD headset_head_unit
pactl set-card-profile $BLUEZCARD a2dp_sink
