#!/bin/bash
if [ `id -u` -ne 0 ]; then
  gk_sudo $0 $@;
  exit
fi

arg="$1"
if [ -z "$arg" ]; then arg="on"; fi
case $arg in
  on|1|true)
    echo "10">/sys/devices/system/cpu/intel_pstate/max_perf_pct
    echo "0">/sys/devices/system/cpu/intel_pstate/min_perf_pct
    dmenu_echo "Activated powersaving mode."
    ;;
  off|0|false)
    echo "100">/sys/devices/system/cpu/intel_pstate/max_perf_pct
    dmenu_echo "Activated performance mode."
    ;;
esac

