#!/bin/bash
# read the abbreviation
xdotool keyup Super;
sleep 0.1s
xdotool key ctrl+shift+Left
xdotool key ctrl+x
# sleep 0.2s # to work reliably in Firefox
SELECTION=`xsel -b`
# read snippet file
cat ~/.snippy/${SELECTION}| xsel -b -i
# paste snippet
xdotool key ctrl+v
xdotool key BackSpace # delete the last blank line, so we stay inline
