#!/bin/bash

DMENU="dmenu"
DMENU_OPTS=($@)
DIR="/home/farzeen/"

if [ ! -d $DIR ]; then
  $DMENU ${DMENU_OPTS[@]} -p "Directory cannot be accessed: $DIR" <&-
  exit 1
fi

IFS=$'\n'

FILES=( $(find "$DIR" -not -ipath "*/.*" -and -not -ipath "*/to_download/*" ) )

if [ -z "$FILES" ]; then
  $DMENU ${DMENU_OPTS[@]} -p "No files found in: $DIR" <&-
  exit 2
fi

FILES_=("${FILES[@]#$DIR}")

TO_OPEN=$($DMENU ${DMENU_OPTS[@]} -i -p "Open file" -l 10 <<<"${FILES_[*]}")

if [ ! -z "$TO_OPEN" ]; then
  if [ ! -e "$DIR/$TO_OPEN" ]; then
    $DMENU ${DMENU_OPTS[@]} -p "Cannot access: $TO_OPEN" <&-
    exit 3
  fi
  xdg-open $DIR/$TO_OPEN &
fi

