#!/bin/bash

DMENU="dmenu"
DMENU_OPTS=($@)

SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

scripts=()

this_script="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
for i in $DIR/*; do
  file=`basename "$i"`
  if [ "$file" = "$this_script" ]; then continue; fi
  scripts+=("$file")
done

if [ -z "$scripts" ]; then
  $DMENU ${DMENU_OPTS[@]} -p "Sorry. You have no scripts in $DIR" <&- >&-
  exit 1
fi

cmd=$( IFS=$'\n' ;$DMENU ${DMENU_OPTS[@]} -i <<< "${scripts[*]}")

if [ $? -eq 0 ]; then
  "$DIR/$cmd" ${DMENU_OPTS[@]}
fi

