#!/bin/bash

DMENU="dmenu"
DMENU_OPTS=($@)
YTDL_DIR=("/home/farzeen/MyDownloaders" "/mnt/gallery/MyDownloaders")

for d in $YTDL_DIR; do 
  if [ ! -d "$d" ]; then
    $DMENU ${DMENU_OPTS[@]} -p "Directory cannot be accessed: $d" <&-
    exit 1
  fi
done

IFS=$'\n'

MKVS=( $(find "${YTDL_DIR[@]}" -iname "*.mkv") )

if [ -z "$MKVS" ]; then
  $DMENU ${DMENU_OPTS[@]} -p "No videos found in: $YTDL_DIR" <&-
  exit 2
fi

for d in ${YTDL_DIR[@]}; do
  echo $d
  MKVS_=("${MKVS[@]#$d}")
done

TO_OPEN=$($DMENU ${DMENU_OPTS[@]} -i -p "Open video" -l 10 <<<"${MKVS_[*]}")

if [ ! -z "$TO_OPEN" ]; then
  if [ ! -f "$YTDL_DIR/$TO_OPEN" ]; then
    $DMENU ${DMENU_OPTS[@]} -p "Cannot access: $TO_OPEN" <&-
    exit 3
  fi
  smplayer $TO_OPEN &
fi

